version: '3.8'

services:
  app:
    image: ubuntu:22.04
    command: tail -f /dev/null
    volumes:
      - /tmp/workspaces/project:/workspaces/project
  odevin:
    image: jsrzic/openhands:latest
    environment:
      SANDBOX_USER_ID: 1005
      WORKSPACE_MOUNT_PATH: /workspaces/project
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/workspaces/project:/opt/workspace_base