version: '3.8'

services:
  app:
    image: ubuntu:22.04
    command: tail -f /dev/null
    volumes:
      - /workspace/project:/workspaces/project
  odevin:
    image: jsrzic/openhands:latest
    environment:
      SANDBOX_USER_ID: 1005
      WORKSPACE_BASE: /workspaces/project
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace/project:/workspaces/project
