version: '3.8'

services:
  app:
    image: ubuntu:22.04
    command: tail -f /dev/null
    volumes:
      - /workspace/project:/workspaces/project
  odevin:
    image: jsrzic/openhands:latest
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: ghcr.io/all-hands-ai/runtime:0.9.2-nikolaik
      SANDBOX_USER_ID: 1000
      WORKSPACE_MOUNT_PATH: /workspaces/project
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace/project:/workspaces/project
